apiVersion: v1
kind: Secret
metadata:
  name: django-app-repo
  namespace: {{ .Values.argocdNamespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: {{ .Values.gitRepoUrl }}