# Default values for django-app

# Application configuration
replicaCount: 2

# Docker image configuration
image:
  repository: "251342503781.dkr.ecr.us-west-2.amazonaws.com/lesson-5-ecr"
  tag: "latest"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

# Horizontal Pod Autoscaler
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

# Environment variables (from .env file)
config:
  DATABASE_NAME: "dinadb"
  DATABASE_USER: "dinauser"
  DATABASE_PASSWORD: "dinapassword"
  DATABASE_HOST: "db"
  DATABASE_PORT: "5432"
  POSTGRES_DB: "dinadb"
  POSTGRES_USER: "dinauser"
  POSTGRES_PASSWORD: "dinapassword"
  DJANGO_PORT: "8000"
  NGINX_PORT: "8080"

# Chart naming
nameOverride: ""
fullnameOverride: ""
